# Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

name: touca-js-release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish-npm:
    name: release-publish-npm
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build:prod
      - name: build package distributable
        run: |
          rm packages/node/README.md
          cp LICENSE packages/node/LICENSE
          cp CHANGELOG.md packages/node/CHANGELOG.md
          cp README.md packages/node/README.md
          sed -i 's/\("main":\).*/\1 "dist\/index.js",/g' packages/node/package.json
          sed -i 's/\("types":\).*/\1 "dist\/index.d.ts",/g' packages/node/package.json
      - run: |
          cd packages/node && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
