version: "3"

services:
  touca_redis:
    image: redis:6-alpine
    volumes:
      - ./local/data/redis:/data
    ports:
      - 6379:6379
    restart: always

  touca_minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    environment:
      MINIO_ROOT_USER: toucauser
      MINIO_ROOT_PASSWORD: toucapass
    volumes:
      - ./local/data/minio:/data
    ports:
      - 9000:9000
    command: server /data
    restart: always

  touca_mongo:
    image: mongo:4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: toucauser
      MONGO_INITDB_ROOT_PASSWORD: toucapass
    volumes:
      - ./local/data/mongo:/data/db
      - ./devops/mongo/mongod.conf:/etc/mongod.conf
      - ./devops/mongo/entrypoint/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    command: --config /etc/mongod.conf
    restart: always
