apiVersion: v2
appVersion: 2.0.0
name: touca
description: Continuous regression testing for critical software workflows
home: https://github.com/trytouca/trytouca
icon: https://touca.io/images/touca_logo_bgwt.png
keywords:
  - regression testing
  - test automation
  - snapshot testing
  - software development lifecycle
maintainers:
  - email: pejman@touca.io
    name: Pejman Ghorbanzade
    url: https://github.com/trytouca/trytouca
sources:
  - https://touca.io
  - https://github.com/trytouca/trytouca/tree/main/ops/k8s
type: application
version: 1.0.0
