apiVersion: v2
appVersion: 1.6.0
name: touca
description: Continuous regression testing for critical software workflows
home: https://github.com/trytouca/trytouca
icon: https://touca.io/logo/touca-logo-w-text-bg.png
keywords:
  - regression testing
  - test automation
  - snapshot testing
  - software development lifecycle
maintainers:
  - email: ehsan@touca.io
    name: Ehsan Ahangari
    url: https://github.com/trytouca/trytouca
sources:
  - https://touca.io
  - https://github.com/trytouca/trytouca/tree/main/ops/k8s
type: application
version: 1.0.0
